apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-operator
  namespace: default
spec:
  channel: alpha
  name: keycloak-operator
  source: community-operators
  sourceNamespace: openshift-marketplace